### ISSUE TITLE
Migration to version 9.0

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/web#240]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-9.0
# Modules to migrate
- [x] help_online - By @lmignon - #378
- [ ] help_popup
- [x] support_branding - ~~By @angelmoya - #430~~ - By @hbrunn - #469 
- [ ] web_action_conditionable - By @ovnicraft - #457 
- [ ] web_advanced_search_wildcard
- [ ] web_advanced_search_x2x - By @Yajo / @cubells - #555
- [ ] web_ckeditor4
- [x] ~~web_color~~ - Replaced by _web_widget_color_
- [ ] web_confirm_window_close
- [ ] web_context_in_colors
- [ ] web_dashboard_open_action
- [ ] web_dashboard_tile - By @nicomacr - #507 
- [ ] web_dialog_size - By @bud-e - #356 
- [ ] web_dom_model_classes
- [x] web_easy_switch_company by @njeudy in #260 
- [x] web_environment_ribbon - By @antespi - #386
- [x] web_export_view - ~~By @rv-clearcorp - #346~~ - By @simahawk - #461 
- [x] web_favicon - Assigned to @pedrobaeza - #344 
- [ ] web_graph_improved
- [ ] web_group_expand - By @JayVora-SerpentCS - #373
- [ ] web_hide_db_manager_link
- [ ] web_invalid_tab - By @kaerdsar - #500 
- [x] web_ir_actions_act_window_message - By @zakiuu - #611 
- [ ] web_ir_actions_act_window_page
- [ ] web_last_viewed_records
- [x] web_listview_custom_element_number - By @legalsylvain - #559 
- [ ] web_listview_show_advanced_search
- [ ] web_m2x_options by ~~@samuellefever in #262~~ @zakiuu in #416
- [ ] web_menu_navbar_needaction
- [ ] web_option_auto_color
- [ ] web_polymorphic_many2one
- [x] web_readonly_bypass - #345
- [ ] web_recipients_uncheck
- [ ] web_search_alphabetic
- [ ] web_search_with_and
- [x] web_searchbar_full_width by @bud-e in #337
- [x] web_send_message_popup @yvaucher in #369
- [x] web_sheet_full_width by @njeudy in #259 
- [ ] web_sheet_full_width_selective
- [ ] web_shortcuts > web_shortcut - By @tarteo - #564 
- [ ] web_switch_company_warning
- [x] web_translate_dialog - By @antespi - #387 
- [x] web_tree_dynamic_colored_field - By @hbrunn - #473 
- [x] web_tree_image by @JayVora-SerpentCS in #290 
- [x] web_tree_many2one_clickable - By @antespi - #456 
- [x] web_widget_color ~~by @llacroix in #270~~ Superseeded by #429 
- [ ] web_widget_datepicker_options - @kellylougheed #539 
- [ ] web_widget_digitized_signature
- [x] web_widget_float_formula - By @obulkin - #425
- [x] web_widget_many2many_tags_multi_selection - https://github.com/OCA/web/pull/312
- [ ] web_widget_one2many_tags
- [ ] web_widget_pattern
- [ ] web_widget_radio_tree - By @kaerdsar - #499 
- [ ] web_widget_text_markdown
- [ ] web_widget_x2many_2d_matrix

**Comment by njeudy** [comment]
How to works ? one merge request by module ? or one big merge request for multiple module ?

**Comment by pedrobaeza** [comment]
One PR by module, please, to ease the review.

**Comment by JayVora-SerpentCS** [comment]
+1

**Comment by JayVora-SerpentCS** [comment]
#290 for web_tree_image

**Comment by jas-odoo** [comment]
I want to contribute.How should I proceed?

**Comment by pedrobaeza** [comment]
Hi, @jas-odoo, tell us which module do you want to migrate for noting here and avoid that other people start to work in the same, and make the PR against the branch when you have it.

**Comment by jas-odoo** [comment]
Hello,
I have already worked on web_widget_many2many_tags_multi_selection and developed it.
I have created branch too but it doesn't allow me to push to same.Is it necessary to submit ICLA form for pushing to same?

**Comment by pedrobaeza** [comment]
You have to make a PR, not to push. You push to your forked branch (personal or company branch), and then propose a PR against OCA branch.

**Comment by jas-odoo** [comment]
:+1: 
Thank you.I will do the same. 
I had migrated 'web_widget_many2many_tags_multi_selection' module.

**Comment by jas-odoo** [comment]
#312 for web_widget_many2many_tags_multi_selection

**Comment by bud-e** [comment]
https://github.com/OCA/web/pull/337  for `web_searchbar_full_width`

**Comment by stellar-pulse** [comment]
https://github.com/OCA/web/pull/341 for web_widget_color

**Comment by pedrobaeza** [comment]
@stellar-pulse, there's already an open PR for this module (#270). Why a new PR?

**Comment by bud-e** [comment]
https://github.com/OCA/web/pull/356 for `web_dialog_size`

**Comment by JayVora-SerpentCS** [comment]
#373 for web_group_expand

**Comment by yvaucher** [comment]
Add #369 and sorted those modules alphabetically

**Comment by lmignon** [comment]
https://github.com/OCA/web/pull/378 for help_online

**Comment by tarteo** [comment]
Hey! Can I migrate web_shortcuts? Do I have to change the name to web_shortcut (singular)?

**Comment by pedrobaeza** [comment]
Yes and yes, please!

**Comment by astirpe** [comment]
Porting of web_shortcuts (renamed to `web_shortcut`) #564
