### ISSUE TITLE
Migration to version 17.0

### ISSUE THREAD

**Issue by legalsylvain** [OCA/web#2661]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-17.0

# Modules to migrate

- [x] web_calendar_slot_duration - By @CRogos - #2786
- [ ] web_chatter_position - By @Jp-alitec - #2826
- [x] web_company_color - By @ArnauCForgeFlow - #3025
- [x] web_dialog_size - By @CarlosRoca13 - #2919
- [x] web_editor_class_selector - By @carlos-lopez-tecnativa - #2991
- [x] web_environment_ribbon - By @rven - #2667
- [x] web_favicon - By @dc-oerp - #2770
- [x] web_field_tooltip - By @manuelregidor - #2892
- [x] web_font_size_report_layout - By @syci - #3371
- [x] web_group_expand - By @astirpe - #2863
- [x] web_ir_actions_act_multi - By @augusto-weiss - #2704
- [x] web_m2x_options - By @manuelregidor - #2888
- [x] web_no_bubble - By @astirpe - #2708
- [x] web_notify - By @trisdoan - #2948
- [x] ~~web_pwa_oca~~ Included in core - Migration script in OCA/OpenUpgrade#4660
- [x] web_refresher - By @LazarusUA - #2669
- [x] web_responsive - By @LazarusUA - #2684
- [x] web_save_discard_button - By @joepsanders - #2872
- [x] web_search_with_and - By @JasminSForgeFlow - #3090
- [x] web_theme_classic - By @legalsylvain - #2660
- [x] web_time_range_menu_custom - By @CarlosRoca13 - #3004
- [x] web_timeline - By @carlos-lopez-tecnativa - #2969
- [x] web_tree_dynamic_colored_field - By @dz0 - #2771
- [x] web_tree_many2one_clickable - By @maciej-wichowski - #2780
- [x] web_widget_bokeh_chart - By @DavidJForgeFlow - #2846
- [x] web_widget_domain_editor_dialog - By @chienandalu - #2875
- [x] web_widget_dropdown_dynamic - By @CarlosRoca13 - #2915
- [x] web_widget_mpld3_chart - By @lef-adhoc - #3000
- [x] web_widget_numeric_step - By @CarlosRoca13 - #2906
- [x] web_widget_open_tab - By @moitabenfdz - #2671
- [x] web_widget_plotly_chart - By @robyf70 - #2815
- [x] web_widget_product_label_section_and_note - By @carlos-lopez-tecnativa - #3080
- [x] web_widget_x2many_2d_matrix - By @SodexisTeam - #2756

Missing module? Check https://github.com/OCA/maintainer-tools/wiki/%5BFAQ%5D-Missing-modules-in-migration-issue-list

**Comment by rven** [comment]
working on **web_environment_ribbon**

**Comment by TesaLazarenko** [comment]
working on **web_refresher**

**Comment by moitabenfdz** [comment]
working on **web_widget_open_tab** #2671

**Comment by TesaLazarenko** [comment]
working on **web_responsive**

**Comment by MaarvynS** [comment]
Hello !, I need the migration of web_widget_x2many_2d_matrix :D
Regards,

**Comment by jeroenev** [comment]
what about web_domain_field? is that no longer needed?

**Comment by pedrobaeza** [comment]
https://github.com/OCA/maintainer-tools/wiki/%5BFAQ%5D-Missing-modules-in-migration-issue-list

**Comment by augusto-weiss** [comment]
mig web_ir_actions_act_multi  #2704

**Comment by astirpe** [comment]
web_no_bubble #2708

**Comment by alielnagar** [comment]
what about web_domain_field!?

**Comment by john-herholz-dt** [comment]
Regarding web_domain_field, I used this module for a dynamic domain.
I just found out, that this seems to work out of the box now in 17.0.

Can somebody confirm this and check the other use cases maybe?
Maybe the module is not needed anymore.

**Comment by cuongnmtm** [comment]
web_remember_tree_column_width https://github.com/OCA/web/pull/2723 (not listed)

**Comment by taikoaudio-odoo** [comment]
How about web_chatter_position? Can/will it be migrated to 17?

**Comment by Nikul-OSI** [comment]
@legalsylvain web_notify: #2747

**Comment by SodexisTeam** [comment]
Migrated web_widget_x2many_2d_matrix #2756

**Comment by jethavadakshal** [comment]
can anyone please review #2769 
thanks

**Comment by maciej-wichowski** [comment]
web_tree_many2one_clickable  #2780

**Comment by nguyenminhchien** [comment]
> Regarding web_domain_field, I used this module for a dynamic domain. I just found out, that this seems to work out of the box now in 17.0.
> 
> Can somebody confirm this and check the other use cases maybe? Maybe the module is not needed anymore.

I found this piece of code https://github.com/odoo/odoo/blob/17.0/addons/account/models/account_tax.py#L1606 . prove that we don't need `web_domain_field` anymore.
![image](https://github.com/OCA/web/assets/8724793/15dbaec6-261e-44a8-ba2e-bd5898bb96fb)
![image](https://github.com/OCA/web/assets/8724793/ac82b1db-e23b-45d5-b903-766633d53438)

**Comment by siemenv** [comment]
web_m2x_options is missing I think, I'll start working on the migration.

**Comment by CRogos** [comment]
**web_listview_range_select** is now working out of the box.

**Comment by CRogos** [comment]
**web_advanced_search** is also now visible in developer mode:
![image](https://github.com/OCA/web/assets/1799080/470f39d1-ac4c-4e02-b249-3e769ef3a9bb)

**Comment by CRogos** [comment]
web_calendar_slot_duration #2786

**Comment by SonoDavid** [comment]
is web_chatter_position not needed any more in v17?

**Comment by peluko00** [comment]
Migrating:

- [web_company_color] https://github.com/OCA/web/pull/2813

**Comment by Paulius11** [comment]
why web_search_with_and is not added in migrate list?

**Comment by achulii** [comment]
web_widget_numeric_step #2825

**Comment by Jp-alitec** [comment]
web_chatter_position #2833

**Comment by Jp-alitec** [comment]
web_select_all_companies #2834

**Comment by Jp-alitec** [comment]
web_select_all_companies #2834 Approved :+1:

**Comment by LoanHuynh** [comment]
> why web_search_with_and is not added in migrate list?

Same question....

**Comment by CRogos** [comment]
I think there is more missing and will be added as soon someone starts with the migration. beside web_search_with_and, these modules are also on my wish list:
web_m2x_options
web_group_expand

**Comment by mohs8421** [comment]
@CRogos I have the need for a newer version of web_m2x_options, so I have partly migrated it, will file a PR later with my changes so far. But at the same time I'm a little stuck as I honestly don't really know about Odoo's client code's architecture and even more on what has changed between 16.0 and 17.0
For reference, here is my PR: https://github.com/OCA/web/pull/2848

**Comment by rven** [comment]
web_m2x_options https://github.com/OCA/web/pull/2847 this PR superseeds https://github.com/OCA/web/pull/2848 and https://github.com/OCA/web/pull/2772

**Comment by astirpe** [comment]
web_group_expand #2863

**Comment by joepsanders** [comment]
Working on web_save_discard_button

**Comment by peluko00** [comment]
Migrating:
- [web_timeline] https://github.com/OCA/web/pull/2874

**Comment by traitrantrobz** [comment]
Working on `web_action_conditionable ` [2896](https://github.com/OCA/web/pull/2896)

**Comment by siemenv** [comment]
Is web_sheet_full_width no longer needed?

**Comment by asr-informatique** [comment]
Hi, any news for the migration of web_pwa_oca in 17.0 ? I don't see any PR opened/closed

**Comment by pedrobaeza** [comment]
PWA is included in core, so no migration will be done.

**Comment by asr-informatique** [comment]
So my bad. Thank you.

**Comment by artstas** [comment]
What about this module - web_pivot_computed_measure?

**Comment by CarlosRoca13** [comment]
> What about this module - web_pivot_computed_measure?

I'm starting working on it @artstas

**Comment by pedrobaeza** [comment]
But for v18

**Comment by techsystech** [comment]
What about web_dark_mode?

**Comment by adrisan0** [comment]
Working on web_ir_actions_act_window_message

**Comment by lef-adhoc** [comment]
web_widget_mpld3_chart #3000

**Comment by Devryc** [comment]
What about list [web_access_rule_buttons](https://github.com/OCA/web/tree/14.0/web_access_rule_buttons)?

**Comment by rolandojduartem** [comment]
is there a problem if I move https://apps.odoo.com/apps/modules/17.0/web_widget_model_viewer_17 here as migration of https://github.com/OCA/web/tree/14.0/web_widget_model_viewer?

**Comment by jtubellac** [comment]
web_select_all_companies #3567 (not listed)
