### ISSUE TITLE
Migration to version 10.0

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/web#435]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-10.0
# Modules to migrate
- [x] help_online - By @lmignon - #526 
- [ ] help_popup - By @daramousk - #624
- [x] support_branding - ~~By @nikiwaibel - #465~~ By @robertrottermann - #465 
- [x] web_access_rule_buttons - By @daramousk - #628 
- [ ] web_action_conditionable - By @daramousk - #635 
- [x] web_advanced_search_wildcard - By @tafaRU - #822 
- [x] web_advanced_search_x2x - By @rami-wafaie - #600
- [ ] web_ckeditor4 - By @daramousk - #820 
- [x] ~~web_color~~ - Replaced by _web_widget_color_
- [x] web_confirm_window_close - By @stefanrijnhart - #631 
- [ ] web_context_in_colors - By @spacemonkeythe - #771 
- [ ] web_dashboard_open_action - By @spacemonkeythe - #770 
- [ ] web_dashboard_tile
- [x] web_dialog_size - By @bud-e - #550 
- [ ] web_dom_model_classes
- [ ] web_duplicate_visibility - By @lmignon - #557 
- [x] ~~web_easy_switch_company~~ (Obsolete) By @legalsylvain #450
- [x] web_editor_background_color - By @Yajo - #665 
- [x] web_environment_ribbon - By @sylvain-garancher - #436 
- [x] web_export_view - By @jlzhou - #444
- [x] web_favicon - By @nikiwaibel - #459 
- [ ] web_graph_improved
- [ ] web_group_expand - By @JayVora-SerpentCS
- [x] web_hide_db_manager_link - by @JayVora-SerpentCS - #571
- [x] web_ir_actions_act_window_message - By @benwillig - #640 
- [x] web_ir_actions_act_window_page - By @StefanRijnhart - #729 
- [ ] web_last_viewed_records - By @JayVora-SerpentCS
- [x] ~~web_listview_custom_element_number~~ Included in core
- [x] web_m2x_options - By @chienandalu - #622
- [ ] web_menu_navbar_needaction - By @hbrunn - #1028 
- [x] web_notify - By @JayVora-SerpentCS - #491 
- [ ] web_option_auto_color
- [ ] web_polymorphic_many2one > web_widget_many2one_polymorphic - By @hbrunn - #884 
- [x] web_readonly_bypass - ~~By @hemnanikalpana - #451~~ By @simahawk - #743 
- [ ] web_recipients_uncheck
- [x] web_responsive - By @lasley - #443 
- [ ] web_search_alphabetic - @JayVora-SerpentCS - #572
- [x] web_searchbar_full_width - By @bud-e - #549 
- [ ] web_send_message_popup - By @njeudy - #504 
- [x] web_sheet_full_width - By @legalsylvain - #449
- [ ] web_sheet_full_width_selective
- [x] web_shortcuts > web_shortcut - By @tarteo - #626 
- [x] web_switch_company_warning - By @hparfr - #722 
- [x] web_timeline - By @LeartS - #521 
- [x] web_translate_dialog - By @JayVora-SerpentCS - #585
- [x] web_tree_dynamic_colored_field - By @jesusVMayor - #638 
- [x] web_tree_image - By @danieltorres7 - #464 
- [x] web_tree_many2one_clickable - By @SodexisTeam - #531 
- [x] web_widget_color - By @adrienpeiffer - #439 
- [x] web_widget_datepicker_options - @kellylougheed
- [x] web_widget_digitized_signature - By @eLBati - #725 
- [x] web_widget_float_formula - By @kellylougheed - #522
- [x] web_widget_image_download - By @smurf-U - #655
- [x] web_widget_image_webcam - By @smurf-U - #649 
- [x] web_widget_many2many_tags_multi_selection - By @fmdl - #623 
- [ ] web_widget_pattern
- [ ] web_widget_text_markdown
- [x] web_widget_timepicker - By @smurf-U - #656 
- [x] web_widget_x2many_2d_matrix - By @jesusVMayor - #606

**Comment by Garamotte** [comment]
Migration of web_environment_ribbon here : https://github.com/OCA/web/pull/436
I added a note in the comment which could be added in the migration page of the wiki.

**Comment by legalsylvain** [comment]
Migration of web_sheet_full_width available here : #449

**Comment by legalsylvain** [comment]
Removing web_easy_switch_company : #450

**Comment by nikiwaibel** [comment]
Migration of web_favicon: https://github.com/OCA/web/pull/459

**Comment by leorochael** [comment]
Migration of web_tree_image: #464

**Comment by JayVora-SerpentCS** [comment]
Working on web_notify #491

**Comment by njeudy** [comment]
web_send_message_popup here #504

**Comment by SodexisTeam** [comment]
Started migration of web_tree_many2one_clickable for 10.0

**Comment by bud-e** [comment]
https://github.com/OCA/web/pull/549 - `web_searchbar_full_width`

**Comment by bud-e** [comment]
https://github.com/OCA/web/pull/550 - `web_dialog_size`

**Comment by tarteo** [comment]
I've started the migration of web_shortcuts / web_shortcut (9.0 https://github.com/OCA/web/pull/564 to 10.0)

**Comment by LeartS** [comment]
`web_listview_custom_element_number` isn't needed in v10 because it's already possible to set any number of records to show.

**Comment by JayVora-SerpentCS** [comment]
web_hide_db_manager_link -> #571

**Comment by JayVora-SerpentCS** [comment]
web_search_alphabetic - Work in Progress #572

**Comment by JayVora-SerpentCS** [comment]
web_group_expand and web_last_viewed_records too

**Comment by lasley** [comment]
Updated, thanks @JayVora-SerpentCS

**Comment by JayVora-SerpentCS** [comment]
web_translate_dialog - #577

**Comment by lasley** [comment]
Updated

**Comment by msadiq1411** [comment]
#601 Can we add this @pedrobaeza as updates will be received soon

**Comment by pedrobaeza** [comment]
Well, when the migration works, then I'll change it.

**Comment by JonathanStein** [comment]
You have mentioned pull request #605 on "web_ir_actions_act_window_page" - it is actually for "web_ir_actions_act_window_message"

**Comment by pedrobaeza** [comment]
Thanks for checking. I have mixed them. Changed.

**Comment by fmdl** [comment]
web_widget_many2many_tags_multi_selectio -> https://github.com/OCA/web/pull/623

**Comment by daramousk** [comment]
help_popup ported on https://github.com/OCA/web/pull/624

**Comment by daramousk** [comment]
web_access_rule_buttons ported https://github.com/OCA/web/pull/628

**Comment by daramousk** [comment]
web_action_conditionable ported https://github.com/OCA/web/pull/635

**Comment by jesusVMayor** [comment]
web_tree_dynamic_colored_field  #638

**Comment by daramousk** [comment]
Porting web_advanced_search_x2x

**Comment by daramousk** [comment]
starting porting web_ckeditor4

**Comment by yajo** [comment]
Are you sure you don't prefer using the bundled summernote editor?

**Comment by smurf-U** [comment]
#649: web_widget_image_webcam

**Comment by smurf-U** [comment]
#655 : migrate web_widget_image_download

**Comment by smurf-U** [comment]
#656 : migrate web_widget_timepicker

**Comment by hparfr** [comment]
#722 : migrate web_switch_company_warning

**Comment by spacemonkeythe** [comment]
Migrating web_dashboard_open_action [#770](https://github.com/OCA/web/pull/770)

**Comment by spacemonkeythe** [comment]
Migrating web_context_in_colors [ #771](https://github.com/OCA/web/pull/771)

**Comment by tafaRU** [comment]
Starting migrating `web_advanced_search_wildcard`.
I cannot see it in the list of modules to migrate. Is it only because it's not been migrated to v9.0?

**Comment by pedrobaeza** [comment]
Yeah, that's the reason.

**Comment by tafaRU** [comment]
`web_advanced_search_wildcard` migrated on https://github.com/OCA/web/pull/822.

**Comment by BT-aestebanez** [comment]
New issue: In Odoo 10.0 the flags 'no_create_edit' and 'no_create' can be used. Without this improvement, they are ignored, and all the views which use this flags are ignored.
Please merge the following PR related to **web_m2o_options**
https://github.com/OCA/web/pull/853
